<template>
  <div><div class="grid-cols-1 grid gap-2.5 [&amp;_&gt;_*]:min-w-0 !gap-3.5"><h1 class="font-claude-response-title mt-1 text-text-100">Пересказ: Принцип Если-то</h1>
    <h2 class="font-claude-response-heading text-text-100 mt-1 -mb-0.5">00:00 --- 00:01:18</h2>
    <p class="font-claude-response-body whitespace-normal break-words">Здравствуйте, друзья, приветствую вас на втором уроке курса, и сегодня мы будем учиться считать варианты. Самый важнейший, базовый принцип расчёта вариантов — это принцип «если-то». Что это значит? Это значит, что когда вы думаете над позицией, вы должны всё время проговаривать: если я пойду так, то соперник пойдёт так.</p>
    <p class="font-claude-response-body whitespace-normal break-words">Кажется, вроде бы ерунда, но мы часто в своих мыслях начинаем строить какие-то фантастические планы: что я пойду сюда, затем сюда, затем сюда, а соперник нас постоянно огорчает. Поэтому алгоритм нашего расчёта всегда будет строиться на простейшей формуле «если-то». Конечно, он обрастёт какими-то тактическими нюансами, сложностями, но базовое правило важнейшее: когда вы считаете вариант, вы обязаны хотя бы один ход соперника точно предвидеть и учитывать.</p>
    <h2 class="font-claude-response-heading text-text-100 mt-1 -mb-0.5">00:01:18 --- 00:02:16</h2>
    <p class="font-claude-response-body whitespace-normal break-words">Давайте посмотрим сейчас на позицию, которую вы видите на экране. Мы играем здесь белыми и попробуем немножко посчитать варианты. Мы не знаем, что нам здесь нужно сделать. Понимаю, что меня смотрят зрители разного уровня подготовки — кто-то сразу увидит правильное решение, а кто-то нет. Давайте попробуем с самых азов посмотреть на эту позицию.</p>
    <img :src="img1" width="300" alt="Image">
    <p class="font-claude-response-body whitespace-normal break-words">Итак, мы смотрим, что к нам в лагерь залез ферзь, и первая же мысль возникает — а что, если попытаться его выиграть? Как выиграть? Напасть на него! Мы смотрим и видим прекрасное нападение <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">Сc4</code>. Если мы не привыкли считать ответ соперника, мы думаем, что уже всё замечательно, но нам очень важно, очень важно знать, что будет после нашего хода.</p>
    <p class="font-claude-response-body whitespace-normal break-words">Первое, что вы должны посмотреть в ответ на свой ход, — это возможность соперника убежать. Если я нападаю, то соперник убегает, и затем мы оцениваем, хорошо это или плохо.</p>
    <h2 class="font-claude-response-heading text-text-100 mt-1 -mb-0.5">00:02:16 --- 00:03:04</h2>
    <p class="font-claude-response-body whitespace-normal break-words">Если мы посмотрим, что мы можем увидеть после хода <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">Сc4</code>, мы увидим, что ферзь убегает — хоть с шахом, хоть без шаха, и получается, нападение у нас оказалось бесцельным, потому что у него была одна только цель — напасть на ферзя. Ферзь убегает, и никаких дополнительных плюшек мы здесь не получаем, да, никаких дополнительных плюсов у нас здесь нет.</p>
    <p class="font-claude-response-body whitespace-normal break-words">Давайте теперь посмотрим в сторону короля. Хотя вот я всегда советую начинать просмотр всё-таки с короля. Здесь нам придётся немножко познакомиться с понятием связки, да, но опять же надеюсь, что все с этим знакомы. Ферзь связывает пешку на <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">g7</code>, значит, эта пешка не может бить ни на поле <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">h6</code>, ни на поле <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">f6</code>.</p>
    <h2 class="font-claude-response-heading text-text-100 mt-1 -mb-0.5">00:03:04 --- 00:04:03</h2>
    <p class="font-claude-response-body whitespace-normal break-words">Чем мы можем воспользоваться и посчитать нападение на мат? <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">Сf6</code> — это ни много ни мало нападение на мат. Мы угрожаем матом <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">Фg7</code>, и опять же: если я нападу на мат, то как соперник будет реагировать? Соперник, давайте проверим, может ли убежать? Да, он может убежать пешкой <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">...g6</code>, но в сравнении с прошлым вариантом мы кое-чего добились. Мы начали обстреливать поля рядом с королём, да и вообще мы как-то центральную диагональ начали очень неплохо обстреливать, поэтому ход <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">Сf6</code> намного лучше хода <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">Сc4</code>. Мы здесь чего-то добились, помимо того, что был шанс поставить мат.</p>
    <h2 class="font-claude-response-heading text-text-100 mt-1 -mb-0.5">00:04:03 --- 00:04:55</h2>
    <p class="font-claude-response-body whitespace-normal break-words">Давайте теперь смотреть. Раз мы так уж заговорили о мате, то напрашивается, наверное, следующий ход — <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">Фg5</code> с идеей <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">Фh6</code> и мата на <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">g7</code>. Напрашивается? Напрашивается.</p>
    <img :src="img1" width="300" alt="Logo">
    <p class="font-claude-response-body whitespace-normal break-words">Давайте теперь посчитаем. Если мы пойдём сюда ставить мат, может ли соперник как-то убежать? Мы обязаны посмотреть бегство короля ходами <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">Лc8</code> и <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">Крf8</code>, но король не успевает. Король не успевает. Почему? Потому что когда наш ферзь окажется на <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">h6</code>, он будет пробивать поле <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">f8</code>, и король никуда не убежит.</p>
    <h2 class="font-claude-response-heading text-text-100 mt-1 -mb-0.5">00:04:55 --- 00:05:30</h2>
    <p class="font-claude-response-body whitespace-normal break-words">Казалось бы, вот оно решение, но когда мы считаем варианты, мы должны убедиться твёрдо, что у соперника нету другой защиты. Если мы пойдём <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">Фg5</code>, сможет ли он за два хода защитить поле <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">g7</code>? Сможет. Если мы идём <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">Фg5</code>, то соперник может пойти <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">...e5</code>, а затем конём на <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">e6</code> прыгнет и защитится от мата.</p>
    <p class="font-claude-response-body whitespace-normal break-words">Жалко, жалко. Хорошая, хорошая была идея, но не работает. Мы учитываем ход соперника — не работает. Если мы не найдём ничего лучше, мы всё равно пойдём сюда, поскольку это позволяет нам хотя бы пешку на <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">е5</code> съесть, но давайте посмотрим, есть ли ещё нападение у нас.</p>
    <h2 class="font-claude-response-heading text-text-100 mt-1 -mb-0.5">00:05:30 --- 00:06:36</h2>
    <p class="font-claude-response-body whitespace-normal break-words">А если мы сейчас нападём на ферзя, только уже не слоном, раскрывая короля, а ладьёй? Ход <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">Лa1</code>! То как пойдёт соперник? И вот внезапно выясняется, что убежать ферзь здесь не может.</p>
    <img :src="img1" width="300" alt="Logo">
    <p class="font-claude-response-body whitespace-normal break-words">Мы при этом не расслабляемся, потому что есть ещё важнейшее правило. Если мы нападаем, то соперник может нанести нам контрудар, то есть какое-нибудь взятие в неожиданном месте. Если мы играем <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">Лa1</code>... ну, здесь взятие было более чем ожидаемо, извините, но мы должны привыкать уже со второго урока проверять две главные вещи: бегство соперника и контрудар.</p>
    <p class="font-claude-response-body whitespace-normal break-words">Есть ли какое-нибудь взятие в другом месте здесь у соперника? Ну, есть взятие <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">...Сxe4</code> с нападением на ферзя. Мы это должны учесть, и нас, в принципе, не сказать чтобы это сильно смущало — у нас есть ход <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">Сxe4</code>, который всё отбивает. В этой позиции промежутка у соперника не нашлось.</p>
    <h2 class="font-claude-response-heading text-text-100 mt-1 -mb-0.5">00:06:36 --- 00:07:36</h2>
    <p class="font-claude-response-body whitespace-normal break-words">Но давайте посмотрим на следующую позицию. Здесь у белых, ну, довольно большой перевес — всё-таки ферзь есть, а у чёрных за этого ферзя получается только конь и слон. Перевес у белых достаточный, вопрос — как играть?</p>
    <img :src="img1" width="300" alt="Logo">
    <p class="font-claude-response-body whitespace-normal break-words">Белые рассчитали прекрасный вариант: как они спасаются от шаха съедением слона, а затем съедают ладью после спасения от шаха. Вы не заметили здесь ошибки в моих рассуждениях? Ошибка, ошибка, и очень большая, заключается в принципе как раз-таки «если-то».</p>
    <p class="font-claude-response-body whitespace-normal break-words">Я сейчас вам рассказал, что я пойду так и так, а не «если я пойду так, то соперник пойдёт по-другому».</p>
    <h2 class="font-claude-response-heading text-text-100 mt-1 -mb-0.5">00:07:36 --- 00:08:35</h2>
    <p class="font-claude-response-body whitespace-normal break-words">И вот когда мы считаем ход <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">Лxe3</code>, то мы должны проверить и очевидный ход. В данном случае бежать некуда чёрным, они будут бить, и взятие <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">...Сxe3</code> нас более чем устраивает, но, как я уже говорил, мы должны учиться проверять промежутки.</p>
    <p class="font-claude-response-body whitespace-normal break-words">Мы должны учиться проверять промежутки! Если мы бьём на <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">e3</code>, то мы обязаны посмотреть не только как он бьёт <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">...Сxe3</code>, но и <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">...Лf1+</code>!</p>
    <img :src="img1" width="300" alt="Logo">
    <p class="font-claude-response-body whitespace-normal break-words">И выясняется, что после <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">...Лf1+</code> нашего короля заманивают под вилку. И вместо победы мы что имеем? Мы имеем баранку. То есть наш лишний ферзь пропал, два лишних коня чёрных остались. Всего-то был нарушен принцип «если-то».</p>
    <h2 class="font-claude-response-heading text-text-100 mt-1 -mb-0.5">00:08:35 --- 00:09:06</h2>
    <p class="font-claude-response-body whitespace-normal break-words">Учитесь, пожалуйста, думать правильно. Если у вас есть время — а я советую всем учиться играть в шахматы всё-таки либо в классику, либо в рапид, к блицу переходить тогда, когда вы уже себя в рапиде чувствуете относительно уверенно — если у вас есть время, старайтесь примерно просчитывать варианты строго по принципу: если я хожу так, то как пойдёт соперник? «Если-то»! Ни в коем случае не «хожу так и так».</p>
    <p class="font-claude-response-body whitespace-normal break-words">Это вот как раз главная ошибка, которая отделяет вас от сильной и успешной игры.</p></div></div>.
</template>
<script setup lang="ts">
import img1 from '@/assets/1.PNG';
</script>