<template>
  <div><div class="grid-cols-1 grid gap-2.5 [&amp;_&gt;_*]:min-w-0 !gap-3.5"><h1 class="font-claude-response-title mt-1 text-text-100">Основы Vue.js 3 — Введение (Пересказ)</h1>
    <h2 class="font-claude-response-heading text-text-100 mt-1 -mb-0.5">Предисловие</h2>
    <p class="font-claude-response-body whitespace-normal break-words">00:00:18 --- Небольшое предисловие к контентной части. Если вы на протяжении трех лет все еще вне политики и считаете, что я не имею права ничего сказать по этому поводу, то, наверное, стоит промотать до контентной части, а возможно и закрыть это видео. Записываю это предисловие в третью годовщину полномасштабного вторжения России в Украину.</p>
    <p class="font-claude-response-body whitespace-normal break-words">00:00:49 --- Видео, которые вы посмотрите, по крайней мере те двадцать, которые вы точно увидите, записаны в Харькове, в пятидесяти-шестидесяти километрах от границы, в 2025 году. К третьему году, мне кажется, кому-то что-то доказывать и рассказывать уже, в общем-то, бесполезно. Все определились, кто, что, где, куда.</p>
    <p class="font-claude-response-body whitespace-normal break-words">00:01:15 --- Без событий, которые происходят, и, главное, без людей, которые оказались рядом, этих видео не было бы. Потому что, очевидно, после полномасштабного вторжения вопрос создания бесплатного контента на русском языке стал ни первым, ни вторым, и даже не четвертым приоритетом. Дело не в отказе от всего русского — продолжаю идентифицировать себя как русского, но не россиянина, этнического русского и частью гражданской нации. Просто банально в нехватке времени, поскольку приоритеты остались совершенно в прошлом. Появились другие приоритеты. <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">Волонтерство</code> стало вопросом номер один. Зарабатывание денег, чтобы донатить на волонтерку, стало вопросом номер два и так далее.</p>
    <p class="font-claude-response-body whitespace-normal break-words">00:02:09 --- Эту серию видео хочу открыть благодарностью, конечно же, прежде всего <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">Силам обороны Украины</code>. Часто говорят вооруженные силы Украины, но прежде всего это силы обороны Украины, потому что это шире, чем просто вооруженные силы. Благодаря которым я жив, благодаря которым три года назад я сидел в бомбоубежище и видел, как рядом напуганы люди, и слышал в буквальном смысле слышал, как летают самолеты и скидывают бомбы на Харьков. Два с половиной года назад буквально каждый день слышал, как по моему городу работает ствольная артиллерия. Сейчас, конечно же, не могу сказать, что все спокойно — шахеды и прочая нечисть прилетает довольно регулярно, но я здесь, я дома и я жив.</p>
    <p class="font-claude-response-body whitespace-normal break-words">00:03:11 --- Вторую, конечно же, благодарность хочу высказать всем тем, кто помогал финансово просто на вооруженные силы в рамках моих сборов, лично мне, и тем ребятам из Армении, благодаря которым и выходит эта серия видео, которые пожелали остаться неизвестными, объясняя, что у некоторых из них остались семьи на территории Российской Федерации. Поэтому мы просто вставили в заставку «тем, кто меня поддерживает». Серия из двадцати видео покрыта как раз ими.</p>
    <p class="font-claude-response-body whitespace-normal break-words">00:03:43 --- Спросил у них, как могу отблагодарить вас за весь тот объем помощи, который вы сделали. Говорят: можешь записать видео на русском языке про Vue 3. Сказал: могу. Дальше — дальше вы всегда можете тоже помочь этой серии видео продолжаться, поддержав лично меня. Конечно же, поддержка вооруженных сил Украины может быть вне закона в вашем регионе, я же ни агент, не нежелательное лицо — подставьте нужное. Подписавшись на Patreon, переведя деньги криптой, чем там еще — Wise, Revolut, какие-то реквизиты я, наверное, оставлю в закрепленном комментарии. Поэтому еще раз всем спасибо, благодаря кому я здесь сейчас жив, нахожусь в добром здравии, в неплохом расположении духа и настроен уверенно.</p>
    <h2 class="font-claude-response-heading text-text-100 mt-1 -mb-0.5">Введение в курс</h2>
    <p class="font-claude-response-body whitespace-normal break-words">00:04:56 --- Давайте начинать. Приступим к записи нового курса или новой версии курса «Как вам комфортнее» по Vue.js 3.</p>
    <p class="font-claude-response-body whitespace-normal break-words">00:05:10 --- За время моего вынужденного радиомолчания, к сожалению, нормального курса, который подсвечивал бы нюансы Vue 3, его особенности и, главное, <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">концептуальные отличия</code> той системы реактивности, которая предлагает Vue от, к примеру, React или Angular — причем неважно, какого Angular, на сигналах или на observables — в общем-то, не появилось. Так что спасибо вам, благодаря вам будем это догонять. Еще пару лет назад искренне бы говорил, что Vue в общем-то неплохой, но мне нравится React.</p>
    <p class="font-claude-response-body whitespace-normal break-words">00:05:53 --- Сейчас не представляю — а сейчас в записи это видео это самое-самое начало 2025 года — не представляю, кто в здравом уме и трезвой памяти добровольно будет брать чистый React. Вопрос холиварный, но тем не менее. Проблема не в том, что React стал хуже. Проблема в том, что React все эти годы, вот приблизительно с момента выхода Vue.js 3.0, <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">стоял на месте</code>, а все другие — под всеми другими подразумеваю Solid, Vue, даже Angular — росли.</p>
    <p class="font-claude-response-body whitespace-normal break-words">00:06:27 --- В итоге, если раньше самым слабым местом в Vue, наверное, была <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">поддержка TypeScript</code>, то сейчас поддержка TypeScript во Vue находится на достойном уровне. Буду честен, она чуть хуже React, и надо немножечко уметь понимать, что и как настраивать, но тем не менее. <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">Экосистема Vue</code> за последние годы устоялась, и она становится все стабильнее и взрослее. Это действительно очень важно, потому что <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">драма перехода</code> со второй на третью версию до сих пор где-то глубоко в моем сердечке, главное — в моем списке задач в GitLab, и боюсь, весь 2025-й она в общем-то там и останется.</p>
    <p class="font-claude-response-body whitespace-normal break-words">00:07:13 --- С другой стороны, надо признать, что если раньше у Vue была объективно <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">лучшая документация</code> из всех фреймворков большой тройки, то с одной стороны документация React подтянулась, а с другой стороны документация Vue, наверное, тоже осталась на месте и поэтому стала хуже. Потому что с появлением <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">Composition API</code> у нас появилось все больше и больше способов сделать это — и под «это» понимаю очень разные вещи. Считаю, что сейчас в документации недостаточно хорошо расставлены акценты.</p>
    <p class="font-claude-response-body whitespace-normal break-words">00:07:37 --- Если раньше документация, наверное, Vue.js 2 представляла собой для меня очень, знаете, такой сбалансированный и, главное, синхронизированный <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">оркестр</code>, то сейчас для меня это звучит, наверное, как <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">бойсбенд, собравшийся на джемсейшн</code>. Если сейчас все термины, которые я вам насыпал, вам ничего не говорят, потому что вы пришли учить Vue, ничего не зная о React, ничего не зная о Vue 2, еще о чем-то — вообще без проблем.</p>
    <p class="font-claude-response-body whitespace-normal break-words">00:08:12 --- Давайте сразу очертим, что необходимо знать для того, чтобы смотреть эти видео.</p>
    <p class="font-claude-response-body whitespace-normal break-words">00:08:31 --- Первое: вы должны знать <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">JavaScript</code> на уровне понимания, что такое функция, цикл и тому подобное, и что такое <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">async-await</code>, потому что без async-await мне будет очень сложно объяснить вам, а чего вот здесь после оператора await мы внезапно оказываемся не внутри компонента. Ну, потому что await условно паузит функцию и так далее.</p>
    <p class="font-claude-response-body whitespace-normal break-words">00:08:57 --- Второе: у вас должен быть минимальный опыт работы со <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">сборщиком</code>. Будем откровенны, как только мы касаемся Vue, говорим «сборщик», подразумеваем <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">Vite</code>, чтобы вы понимали, что такое файлики, как работает система сборки и так далее. Опять же, минимальный опыт, ничего глобального мы настраивать не будем. А что же мы делать-то будем и что мы будем учить? Вначале думал такое, что уложусь рассказать современный Vue буквально за два-три видео, но потом, знаете, сел и думаю: значит так, а что, собственно, давайте подумаем, мне надо рассказать.</p>
    <p class="font-claude-response-body whitespace-normal break-words">00:09:38 --- Конечно же, Vue зиждется на <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">двух фундаментальных концепциях</code>. Это <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">реактивность</code> и <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">декларативность</code>. Под декларативностью правильнее бы, наверное, называть <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">декларативный DOM</code>, потому что декларативность — это очень философское понятие. Две основные наши конструкции: реактивность — это <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">способность системы реагировать на изменения</code>, и реактивность во Vue достаточно сложная и интересная. И после этого — декларативный DOM. Как только на этих двух столбах у нас зиждется основное, что есть в любом современном фреймворке.</p>
    <p class="font-claude-response-body whitespace-normal break-words">00:10:22 --- Это, конечно же, <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">компоненты</code>. Мы дробим наше приложение на маленькие кусочки, подобные HTML-тегам, и таким образом мы боремся со сложностью. То есть, с одной стороны, вы же, когда пишете тег video, вы не думаете о том, что тег video — это на самом деле куча хитрых нюансов, как там рендерится, кнопочки управления и так далее. Нет, тег video, передали в него вход, тег video генерирует нам события — и вперёд.</p>
    <p class="font-claude-response-body whitespace-normal break-words">00:10:51 --- Кстати, о событиях. Как только мы говорим о компонентах, мы должны поговорить ещё о пачке вещей. И об этих вещах, знаете, наверное, не пришлось бы говорить, если бы не было так много людей, <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">покусанных React</code>.</p>
    <p class="font-claude-response-body whitespace-normal break-words">00:11:08 --- Почему? Потому что будем говорить о <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">пропсах</code>, и здесь, опять же, правильнее, наверное, говорить о <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">пропсах и атрибутах</code>, потому что люди, даже которые имеют сколько-то времени в Vue-стеке, иногда не могут мне даже ответить, в чем разница между пропсами и атрибутами.</p>
    <p class="font-claude-response-body whitespace-normal break-words">00:11:33 --- Конечно же, о <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">событиях</code>, конечно же, о <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">слотах</code>. И, вы знаете, раньше, если бы мы жили в идеальном мире, где люди изначально изучают базу, нас бы было бы круто, потому что что пропсы, что события, что слоты существуют в <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">веб-компонентах</code>, и Vue очень сильно вдохновлялся концепцией веб-компонентов. Во Vue 3 еще, так, знаете, на легкую радость React-разработчикам, <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">события и пропсы стали</code> на самом деле <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">между собой очень тесно связаны</code>.</p>
    <p class="font-claude-response-body whitespace-normal break-words">00:12:09 --- На этом тоже надо акцентировать отдельное внимание, потому что без этого, ну, скажем так, будут возникать определенные нюансы. Также, как только мы разберемся с тем, зачем нам нужны пропсы, атрибуты, события и слоты — на этом пункте особенно тяжело React-разработчикам, потому что у React-разработчиков все есть по сути пропс, передается вниз функция, а тут, о боже, <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">передавать функцию в компонент не очень хорошо</code>, и даже передавать компонент в компонент не очень хорошо, хотя иногда можно и нужно — то на самом деле у нас нам придется с этим разобраться.</p>
    <p class="font-claude-response-body whitespace-normal break-words">00:12:35 --- И потом мы захотим расширять наши компоненты еще одним инструментом, который есть во Vue. Если props — это просто как HTML-атрибуты, если события вам знакомы из обычных JavaScript-овых событий, если слоты — это, грубо говоря, <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">дырки в компоненте</code>, куда можно вставлять вещи, то...</p>
    <hr class="border-border-300 my-2">
    <p class="font-claude-response-body whitespace-normal break-words"><em>Примечание: Транскрипт обрывается на этом месте. Автор планировал продолжить объяснение дополнительных инструментов расширения компонентов.</em></p></div></div>
  <div><div class="grid-cols-1 grid gap-2.5 [&amp;_&gt;_*]:min-w-0 !gap-3.5"><h1 class="font-claude-response-title mt-1 text-text-100">Основы Vue — Введение (Продолжение)</h1>
    <h2 class="font-claude-response-heading text-text-100 mt-1 -mb-0.5">Декларативный DOM и директивы</h2>
    <p class="font-claude-response-body whitespace-normal break-words"><strong>00:13:13</strong> --- Итак, я написал здесь <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">декларативный DOM</code>. Что же это такое? По сути, это возможность расширять наш HTML новыми атрибутами, которые добавляют поведение элементам. У Vue есть очень важная способность добавлять такие атрибуты, что делает разработку гибкой и выразительной.</p>
    <p class="font-claude-response-body whitespace-normal break-words"><strong>00:13:30</strong> --- Пока что я упрощаю — эти атрибуты называются <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">директивы</code> (если говорить о компонентах более точно). И помните классическую фразу: "из всех искусств для нас важнейшим является кино"? Так вот, из всех директив для нас важнейшей является <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">V-model</code>. Она определяет суть работы с компонентами. В каком смысле? Большинство наших компонентов мы будем связывать между собой именно с использованием <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">ViewModel</code> — паттерна двусторонней привязки данных.</p>
    <p class="font-claude-response-body whitespace-normal break-words"><strong>00:13:58</strong> --- Очень важно понимать, как работает V-model, потому что во Vue 3 произошли серьезные изменения. Если раньше во Vue 2 у нас были странные извращения вроде Props, PropSync и тому подобное, то теперь остались только <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">множественные модели</code>. И я вижу, что даже опытные разработчики на Vue до сих пор не используют эту возможность в полной мере.</p>
    <p class="font-claude-response-body whitespace-normal break-words"><strong>00:14:18</strong> --- Как только мы познаем всю мощь того, что можно написать в компонентах, обращаю внимание — я осознанно, для тех, кто уже опытный, не упоминаю в высокоуровневой структуре лекций мелкие вещи, которые можно рассказать за 10 минут, просто дав ссылку на документацию. К примеру, <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">жизненный цикл компонента</code>. Несомненно, его надо коснуться, но ничего магического там нет. А вот что действительно магическое?</p>
    <p class="font-claude-response-body whitespace-normal break-words"><strong>00:14:52</strong> --- Как только у нас появляется вся мощь разработки на Vue, мы хотим эту мощь обуздать и правильно структурировать. И если HTML мы учимся дробить на маленькие компоненты, то внутри самих компонентов мы учимся строить отдельные кусочки функциональности, которые называются <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">композаблами</code> (composables). Поговорим, чем это отличается от хуков React. И хотя внешне они выглядят достаточно похоже, философски <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">композаблы Vue</code> существенно отличаются от реакт-хуков. Это очень важно понимать, если мы хотим писать эффективные композаблы.</p>
    <img :src="img1" width="300" alt="Image" loading="lazy">
    <p class="font-claude-response-body whitespace-normal break-words">[SCREENSHOT: Схема структуры курса на экране — визуальное представление всех тем и их взаимосвязей, которые будут рассматриваться в серии видео]</p>
    <p class="font-claude-response-body whitespace-normal break-words"><strong>00:15:24</strong> --- Как только мы начнем использовать всю нашу мощь из всех инструментов, которые перед вами на экране, у нас сразу возникает очень важная тема, которую мы обязательно затронем. Обычно необходимость в ней появляется сразу после изучения композаблов — это <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">отладка</code>.</p>
    <p class="font-claude-response-body whitespace-normal break-words"><strong>00:15:42</strong> --- Как связаны композаблы и отладка? К примеру, через проблему <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">потери реактивности</code>. Это ужас, который преследовал всех разработчиков на Vue 2. Во Vue 3 потерять реактивность стало сложнее, но всё ещё возможно. Например, многие сравнительно бездумно деструктурируют props и получают неожиданные результаты. Конечно же, отладка относится не только к композаблам — мы должны уметь отлаживать и компоненты, поэтому здесь всё взаимосвязано.</p>
    <img :src="img2" width="300" alt="Image" loading="lazy">
    <p class="font-claude-response-body whitespace-normal break-words">[SCREENSHOT: Реорганизация диаграммы структуры курса — перемещение блока "Директивы" выше по схеме для демонстрации логического потока изучения материала]</p>
    <p class="font-claude-response-body whitespace-normal break-words"><strong>00:16:18</strong> --- Как только мы начинаем говорить о композаблах, всплывает оно — волшебное слово, от которого у половины людей текут слюнки. Это "архитектура". Давайте перенесем директивы повыше, и тогда у нас получится вот такая структура.</p>
    <h2 class="font-claude-response-heading text-text-100 mt-1 -mb-0.5">Архитектура и правильные практики</h2>
    <p class="font-claude-response-body whitespace-normal break-words"><strong>00:16:42</strong> --- Почему архитектура? Потому что людям всегда кажется, что они чего-то не знают. Но мне не нравится термин "архитектура" — я не буду его использовать. Вместо этого я расскажу, <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">как правильно</code> делать целый ряд вещей, отвечая на конкретные практические вопросы.</p>
    <p class="font-claude-response-body whitespace-normal break-words"><strong>00:17:06</strong> --- Как, извините за сложность, правильно писать <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">композаблы</code>? Потому что половина людей... Как проверить себя, что вы знаете ответ на этот вопрос? К примеру, можете ли вы ответить на вопрос: когда и зачем вам в композаблах будет нужен в реальной жизни <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">shallowRef</code>? И зачем вообще существует <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">maybeRef</code>? Почему так принято, чтобы композаблы в идеале принимали maybeRef?</p>
    <p class="font-claude-response-body whitespace-normal break-words"><strong>00:17:41</strong> --- Второй вопрос, конечно же: <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">как дробить компоненты</code>? По каким критериям разбивать на кусочки? Когда надо делать компонент, а когда — композабл? Как правильно <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">вызывать API</code> и работать с внешними сервисами?</p>
    <p class="font-claude-response-body whitespace-normal break-words"><strong>00:17:59</strong> --- Естественно, тоже такой традиционный, избитый вопрос: как во Vue <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">интегрировать</code> очередную библиотеку и так далее. Давайте двигаться дальше.</p>
    <p class="font-claude-response-body whitespace-normal break-words"><strong>00:18:28</strong> --- Самое-самое важное — <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">обработка ошибок</code>. Это то, что, наверное, отличает начинающего разработчика от эксперта. Обязательно надо рассмотреть, как правильно обрабатывать ошибки. И конечно же, мы не могли не включить в этот курс еще одну вещь, которая нужна очень и очень редко, но когда она нужна, вам необходимо это знать.</p>
    <p class="font-claude-response-body whitespace-normal break-words"><strong>00:19:00</strong> --- Это вопрос о том, когда от props стоит переходить к использованию нашего горячо любимого <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">Provide/Inject</code> и зачем это нам может быть нужно.</p>
    <p class="font-claude-response-body whitespace-normal break-words"><strong>00:19:14</strong> --- И last, but not least — после разговора обо всем этом мы обязательно должны поговорить о широкой <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">экосистеме</code>. В наших видео — давайте я просто назову это экосистемой — всего того, что я сейчас перечислю, мы будем касаться только краешком. Видео будут посвящены исключительно Vue, но обязательно надо поговорить о <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">Pinia</code>. Обязательно надо поговорить о <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">TanStack Query</code>, пробелы важны, или <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">Pinia Colada</code> — альтернатива TanStack Query.</p>
    <p class="font-claude-response-body whitespace-normal break-words"><strong>00:19:58</strong> --- Обязательно, конечно же, надо поговорить о <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">Vue Router</code>. И в принципе, наверное, всё. Я осознанно не буду касаться вопросов экосистемы <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">Vuex</code>, потому что он устарел.</p>
    <p class="font-claude-response-body whitespace-normal break-words"><strong>00:20:17</strong> --- Я осознанно не буду касаться экосистемы <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">Nuxt</code>, потому что про это надо делать отдельное видео. Посмотрим, возможно в дальнейшем, если будет интерес, мы про него обязательно поговорим. Но вот те ключевые темы, которые я считаю необходимыми для рассмотрения в базовых видео. Под всё это я отвожу где-то 20 видео, которые будут выходить.</p>
    <h2 class="font-claude-response-heading text-text-100 mt-1 -mb-0.5">Практическое задание и детали курса</h2>
    <p class="font-claude-response-body whitespace-normal break-words"><strong>00:20:45</strong> --- В том темпе, в котором я их буду записывать. А если вы это видео смотрите уже на YouTube, то в течение пары месяцев эти видео попадут туда в том или ином виде. Спасибо всем тем, кто разрешил мне это сделать по прошествии определенного времени. На что еще стоит обратить внимание? Мы будем использовать <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">TypeScript</code>, мы будем использовать <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">Composition API</code>.</p>
    <p class="font-claude-response-body whitespace-normal break-words"><strong>00:21:13</strong> --- Хотелось бы мне того или нет — и то, и другое победило. И поскольку моя задача давать вам релевантные знания, мы будем ориентироваться на них. Следующее: как понять, что вы всё это базовое уже знаете и не надо тратить время? Очень легко! Вы берете таймер, находите три часа свободного времени. Поверьте, даже если вы справитесь с заданием, оно того стоит.</p>
    <p class="font-claude-response-body whitespace-normal break-words"><strong>00:21:43</strong> --- Очень прикольное и развивающее задание.</p>
    <img :src="img3" width="300" alt="Image" loading="lazy">
    <p class="font-claude-response-body whitespace-normal break-words">[SCREENSHOT: Открытая документация библиотеки ShardCN View с навигацией к разделу Auto Form — демонстрация известной библиотеки компонентов, адаптированной для Vue]</p>
    <p class="font-claude-response-body whitespace-normal break-words">Открываете <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">ShardCN View</code>. Это очень известная библиотека компонентов ShardCN, адаптированная для Vue, но вас она не очень интересует сама по себе. Вас интересует секция <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">Auto Form</code>.</p>
    <p class="font-claude-response-body whitespace-normal break-words"><strong>00:22:09</strong> --- Что такое секция Auto Form?</p>
    <img :src="img4" width="300" alt="Image" loading="lazy">
    <p class="font-claude-response-body whitespace-normal break-words">[SCREENSHOT: Пример кода Zod-схемы с определениями правил валидации для различных полей формы, показывающий структуру описания формы через схему]</p>
    <p class="font-claude-response-body whitespace-normal break-words">Фактически перед вами задание, которое вы можете сколько угодно упростить, но суть в чем: вы пишете схему с использованием <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">Zod</code>, которая описывает правила валидации вашей формы.</p>
    <p class="font-claude-response-body whitespace-normal break-words"><strong>00:22:35</strong> --- Дальше вы передаете вашу схему в компонент, который вам необходимо написать — <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">AutoForm</code>.</p>
    <img :src="img5" width="300" alt="Image" loading="lazy">
    <p class="font-claude-response-body whitespace-normal break-words">[SCREENSHOT: Автоматически сгенерированная красивая форма с полями, созданными на основе Zod-схемы — визуализация того, как правила валидации преобразуются в UI-элементы]</p>
    <p class="font-claude-response-body whitespace-normal break-words">Он генерирует вам автоматически вот такую красивую форму из схемы, где мы описываем правила валидации. Сами компоненты вы, конечно же, можете взять из условного ShardCN или откуда угодно, или даже воспользоваться дефолтными. Но суть в том, что вы, во-первых, автоматически разбираете код Zod для того, чтобы сгенерировать во Vue динамически такую форму.</p>
    <p class="font-claude-response-body whitespace-normal break-words"><strong>00:23:09</strong> --- Во-вторых, ваша форма обязательно содержит возможности кастомизации. Что такое возможности кастомизации? У нас есть, к примеру, поле <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">Accept Terms</code>. В нашей схеме это просто boolean — булево значение. По умолчанию оно выводится чекбоксом.</p>
    <p class="font-claude-response-body whitespace-normal break-words"><strong>00:23:27</strong> --- У нас есть поле <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">custom parent</code> — какая-то строка.</p>
    <img :src="img6" width="300" alt="Image" loading="lazy">
    <p class="font-claude-response-body whitespace-normal break-words">[SCREENSHOT: Демонстрация кастомизации полей формы через scoped slots — поле Accept Terms преобразовано из простого чекбокса в сложный компонент с галочкой, текстом и дополнительной ссылкой; поле custom parent показано как специальный компонент с инпутом и кнопкой "check"]</p>
    <p class="font-claude-response-body whitespace-normal break-words">В нашем компоненте AutoForm мы передаем <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">scoped slot</code> для accept terms, который позволяет нам сделать так, чтобы accept terms выводилось не просто чекбоксом, а вот так: галочка, текст, дополнительная ссылка.</p>
    <p class="font-claude-response-body whitespace-normal break-words"><strong>00:23:46</strong> --- Custom parent выводится как особый компонент с инпутом, в котором есть кнопка "check", которая что-то делает, и так далее. То есть это компонент формы, который разбирает — я взял Zod, потому что, к примеру, про него искусственный интеллект знает, вы можете спокойно использовать AI для решения этой задачи, если вам нравится.</p>
    <p class="font-claude-response-body whitespace-normal break-words"><strong>00:24:22</strong> --- В вашем компоненте AutoForm вы предоставляете возможность кастомизации формы, чтобы я мог продолжать ей пользоваться, ловя события submit.</p>
    <img :src="img7" width="300" alt="Image" loading="lazy">
    <p class="font-claude-response-body whitespace-normal break-words">[SCREENSHOT: Код компонента AutoForm с передачей props — показана структура тега автоформ с передачей Zod-схемы через prop schema, конфигурацией полей через fieldConfig, и генерацией события submit с корректной валидацией]</p>
    <p class="font-claude-response-body whitespace-normal break-words">Ключевые моменты: тег <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">&lt;AutoForm&gt;</code>, в него передается наша Zod-схема через prop <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">schema</code>, также передается <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">fieldConfig</code> — дополнительные атрибуты для каждого поля схемы. При сабмите генерируется событие <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">submit</code>. При этом все ваши валидации корректно работают, в том числе с кастомными правилами и кастомными компонентами формы.</p>
    <p class="font-claude-response-body whitespace-normal break-words"><strong>00:24:51</strong> --- Мне очень нравится это задание, потому что оно демонстрирует всю мощь Vue. <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">Реактивность</code> проявляется, конечно же, везде — формы, формы, приправленные формами. У нас очень хорошо проявляется здесь ваше понимание <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">слотов</code>, <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">scoped slots</code>, того, как организованы взаимодействия и потоки данных.</p>
    <p class="font-claude-response-body whitespace-normal break-words"><strong>00:25:15</strong> --- Здесь, как минимум в том варианте, который я написал для решения этой задачи, мне даже понадобился <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">Provide/Inject</code>. Ставь лайк, если ты знаешь, зачем он мне здесь понадобился! И здесь точно так же очень хорошо проявляется понимание относительно редкой и чуть более сложной ситуации, когда <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">слоты динамичны</code> и зависят от данных, которые приходят к нам. Это очень хорошая ситуация для понимания Vue.</p>
    <p class="font-claude-response-body whitespace-normal break-words"><strong>00:25:46</strong> --- Вот такая практика. Мы фактически будем разбирать в начале другие задачки, попроще и поближе к реальным задачам. А в конце обязательно уделим одно, два, три — посмотрим, как получится — видео именно решению этой задачи, как квинтэссенции и агрегации знаний нашего базового Vue.</p>
    <p class="font-claude-response-body whitespace-normal break-words"><strong>00:26:11</strong> --- Наша задача: из той схемы, которая у меня здесь есть, собрать знания и научиться их применять для решения вот этой задачи. Собственно, на этом по структуре знаний у нас всё. Желаю вам удачи, творческих успехов и погнали!</p>
    <h2 class="font-claude-response-heading text-text-100 mt-1 -mb-0.5">Сообщество и поддержка</h2>
    <p class="font-claude-response-body whitespace-normal break-words"><strong>00:26:37</strong> --- Немного послесловия. Первое: у нас давным-давно существует Telegram-чат <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">UGS Club</code>, где вам всегда будут рады ответить на вопросы. Не стесняйтесь задавать любые самые глупые вопросы по этой серии видео, если вам что-то непонятно. Самое тупое, что вы можете сделать, это не задать вопрос и остаться в неведении.</p>
    <p class="font-claude-response-body whitespace-normal break-words"><strong>00:27:04</strong> --- После того как мы запишем несколько видео, я, наверное, запишу такую вставку из серии "как правильно задавать вопросы", чтобы нам с вами было легче взаимодействовать. Но не стесняйтесь оставлять комментарии, публиковать и продвигать эти видео везде, где можно — мне будет приятно.</p>
    <p class="font-claude-response-body whitespace-normal break-words"><strong>00:27:28</strong> --- И увидимся уже в следующих видео. Возможно, дальше будут такие вставки, возможно нет. Посмотрим. Давайте, давайте начинать. Дальше...</p></div></div>
</template>
<script setup lang="ts">
import img1 from '@/assets/vuedush/vuedush0/1.PNG';
import img2 from '@/assets/vuedush/vuedush0/2.PNG';
import img3 from '@/assets/vuedush/vuedush0/3.PNG';
import img4 from '@/assets/vuedush/vuedush0/4.PNG';
import img5 from '@/assets/vuedush/vuedush0/5.PNG';
import img6 from '@/assets/vuedush/vuedush0/6.PNG';
import img7 from '@/assets/vuedush/vuedush0/7.PNG';
</script>